### ISSUE TITLE
Collaboration on this project.

### ISSUE THREAD

**Issue by expertcoder** [demian-wolf/ReversoAPI#1]
Hi,

Just letting you know I am using this git repository as part of another hobby project which I am working on. I am happy to contributes to the repository if you are interested.

I am using this "issue" feature as I don't have any other way to reach you.

I am a senior software engineer from Australia, I am presently studying Russian in Minsk. I notice that you know Ukrainian and Russian languages.

Presently I am working on a few hobby projects to assist with language learning, it seems you are working on similar projects also.

Feel free to email me via the email address on my GitHub profile.
https://github.com/expertcoder

Thanks.

**Comment by demian-wolf** [comment]
Hi. I have answered in an e-mail message.
